config/routes.rb
Rails.application.routes.draw do
  

  resources :genereate_urls do
    collection do
      post :genereate_short_url
    end
  end

  devise_for :users
  resources :mes

   root 'genereate_urls#index'

    get '/:id' => "shortener/shortened_urls#show"

end

app/models/genereate_url.rb
class GenereateUrl < ActiveRecord::Base
	has_shortened_urls
end

app/models/me.rb
class Me < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user! 
	protect_from_forgery with: :exception
end

app/controllers/genereate_urls_controller.rb
class GenereateUrlsController < ApplicationController
  before_action :set_genereate_url, only: [:show, :edit, :update, :destroy]

  # GET /genereate_urls
  # GET /genereate_urls.json
  def index
    @genereate_urls = GenereateUrl.all
  end

  def genereate_short_url
      url = params[:url_name] 
        new_url = Shortener::ShortenedUrl.generate(url)
        @converted_url = new_url.unique_key
        respond_to do |format|
          format.json { render json: new_url.to_json }
        end

      # respond_to do |format|
      #   redirect_to genereate_urls_path
      #   format.js
      # end 
   
  end

  # GET /genereate_urls/1
  # GET /genereate_urls/1.json
  def show
  end

  # GET /genereate_urls/new
  def new
    @genereate_url = GenereateUrl.new
  end

  # GET /genereate_urls/1/edit
  def edit
  end

  # POST /genereate_urls
  # POST /genereate_urls.json
  def create
    @genereate_url = GenereateUrl.new(genereate_url_params)

    respond_to do |format|
      if @genereate_url.save
        format.html { redirect_to @genereate_url, notice: 'Genereate url was successfully created.' }
        format.json { render :show, status: :created, location: @genereate_url }
      else
        format.html { render :new }
        format.json { render json: @genereate_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genereate_urls/1
  # PATCH/PUT /genereate_urls/1.json
  def update
    respond_to do |format|
      if @genereate_url.update(genereate_url_params)
        format.html { redirect_to @genereate_url, notice: 'Genereate url was successfully updated.' }
        format.json { render :show, status: :ok, location: @genereate_url }
      else
        format.html { render :edit }
        format.json { render json: @genereate_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genereate_urls/1
  # DELETE /genereate_urls/1.json
  def destroy
    @genereate_url.destroy
    respond_to do |format|
      format.html { redirect_to genereate_urls_url, notice: 'Genereate url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genereate_url
      @genereate_url = GenereateUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genereate_url_params
      params.require(:genereate_url).permit(:url_name)
    end
end

app/controllers/mes_controller.rb
class MesController < ApplicationController
  before_action :set_me, only: [:show, :edit, :update, :destroy]

  # GET /mes
  # GET /mes.json
  def index
    @mes = Me.all
  end

  # GET /mes/1
  # GET /mes/1.json
  def show
  end

  # GET /mes/new
  def new
    @me = Me.new
  end

  # GET /mes/1/edit
  def edit
  end

  # POST /mes
  # POST /mes.json
  def create
    @me = Me.new(me_params)

    respond_to do |format|
      if @me.save
        format.html { redirect_to @me, notice: 'Me was successfully created.' }
        format.json { render :show, status: :created, location: @me }
      else
        format.html { render :new }
        format.json { render json: @me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mes/1
  # PATCH/PUT /mes/1.json
  def update
    respond_to do |format|
      if @me.update(me_params)
        format.html { redirect_to @me, notice: 'Me was successfully updated.' }
        format.json { render :show, status: :ok, location: @me }
      else
        format.html { render :edit }
        format.json { render json: @me.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mes/1
  # DELETE /mes/1.json
  def destroy
    @me.destroy
    respond_to do |format|
      format.html { redirect_to mes_url, notice: 'Me was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_me
      @me = Me.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def me_params
      params.require(:me).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genereate_urls_helper.rb
module GenereateUrlsHelper
	
end

app/helpers/mes_helper.rb
module MesHelper
end

app/views/genereate_urls/_form.html.erb
<%= form_for(@genereate_url) do |f| %>
  <% if @genereate_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genereate_url.errors.count, "error") %> prohibited this genereate_url from being saved:</h2>

      <ul>
      <% @genereate_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_name %><br>
    <%= f.text_field :url_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genereate_urls/edit.html.erb
<h1>Editing genereate_url</h1>

<%= render 'form' %>

<%= link_to 'Show', @genereate_url %> |
<%= link_to 'Back', genereate_urls_path %>

app/views/genereate_urls/index.html.erb
<h1>Genereate URL</h1>

<table align="center">
  <thead style="padding-right:15px">
    <tr>
      <th>Url Name</th>
      <th>Prees button to change</th>
      <th>Changed URL Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>    
      <tr>        
        <td><%= text_area_tag(:url_name, "",size: "24x2") %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;<%= button_tag ("Chane URL"), :onclick=> "create_short_url();" ,:class=> 'btn btn-success create_url'%></td>
        <td><div><%= text_area_tag(:new_url_name, "",size: "24x2") %></div></td>
        </td>
      </tr>    
  </tbody>
</table>
<br>



<script type="text/javascript"> 

  function create_short_url(){
   var url_name = ($('#url_name').val())
   $.ajax({
      dataType: 'JSON',
      type: "POST",
      url: "/genereate_urls/genereate_short_url/",
      data:{url_name: url_name},
       success: function(data) {
        $('#new_url_name').val("http://localhost:4000/" + data.unique_key +" ");
      }
   })
  }


</script>

app/views/genereate_urls/new.html.erb
<h1>New genereate_url</h1>

<%= render 'form' %>

<%= link_to 'Back', genereate_urls_path %>

app/views/genereate_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url name:</strong>
  <%= @genereate_url.url_name %>
</p>

<%= link_to 'Edit', edit_genereate_url_path(@genereate_url) %> |
<%= link_to 'Back', genereate_urls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= link_to "Logout" , destroy_user_session_path ,:method=>"delete"%>
  <title>Gogo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mes/_form.html.erb
<%= form_for(@me) do |f| %>
  <% if @me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@me.errors.count, "error") %> prohibited this me from being saved:</h2>

      <ul>
      <% @me.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mes/edit.html.erb
<h1>Editing me</h1>

<%= render 'form' %>

<%= link_to 'Show', @me %> |
<%= link_to 'Back', mes_path %>

app/views/mes/index.html.erb
<h1>Listing mes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mes.each do |me| %>
      <tr>
        <td><%= me.name %></td>
        <td><%= link_to 'Show', me %></td>
        <td><%= link_to 'Edit', edit_me_path(me) %></td>
        <td><%= link_to 'Destroy', me, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Me', new_me_path %>

app/views/mes/new.html.erb
<h1>New me</h1>

<%= render 'form' %>

<%= link_to 'Back', mes_path %>

app/views/mes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @me.name %>
</p>

<%= link_to 'Edit', edit_me_path(@me) %> |
<%= link_to 'Back', mes_path %>